@startuml

actor User
participant GUI
participant CampaignController
participant CampaignService
database DB


User -> GUI: Exit Campaign
activate GUI
GUI -> CampaignController : requestExit()
activate CampaignController
CampaignController -> CampaignService : validateExit()
activate CampaignService

CampaignService -> CampaignService : checkIfInBattle()

alt NOT in battle
    CampaignService -> DB : Update progress(party, level, status, room, inventory)
    activate DB
    DB --> CampaignService : success
    deactivate DB

    CampaignService --> CampaignController : Exit Approved
    CampaignController --> GUI : returnToMainMenu()
    GUI --> User : display main menu
else in battle
    CampaignService --> CampaignController : Exit Denied
    CampaignController --> GUI: showError("Cannot exit during battle")
end

deactivate CampaignService
deactivate CampaignController
@enduml