@startuml
actor User
participant GUI
participant CampaignController
participant CampaignService
database DB

User -> GUI : Continue PVE
activate GUI
GUI -> CampaignController : loadCampaign(userID)
activate CampaignController
CampaignController -> CampaignService : fetchCampaign(userID)
activate CampaignService
CampaignService -> DB : SELECT campaign data
activate DB
DB --> CampaignService : campaign progress
deactivate DB

CampaignService -> CampaignService : reconstructCampaign()
CampaignService --> CampaignController : campaignState
deactivate CampaignService

CampaignController --> GUI : loadCampaignView(campaingState)

alt lastRoom = Battle
    GUI --> User : Display Battle View
else lastRoom = Inn
    GUI --> User : Display Inn View
end

deactivate CampaignController
deactivate GUI
@enduml